name: Judge-Test-GCE

on:
  push:
    branches:
      - patch/ci

jobs:
  judge-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - id: build-docker-images
      name: Build docker images
      run: ./build.sh      
      working-directory: ./langs

    - id: judge-test
      name:	Run judge test
      run: go test -v .
      working-directory: ./judge
